### ISSUE TITLE
Can't compile example with gccgo

### ISSUE THREAD

**Issue by BrycensRanch** [jwijenbergh/puregotk#9]
Hi! I'd like to say thank you for all of your work. I was trying to use diamond's gotk4 example until it took 12 minutes and some change to build because of `cgo` (made me reconsider my life choices)

I found your binding and it works really well! It's much smaller than binaries produced by diamond's gotk4 example thanks to no `cgo`. I wanted to see if I could create a dynamically linked binary for Linux distributions that already have the libraries installed (dynamically linked) and I saw that the `gccgo` compiler does that and makes the binary even smaller. 

Now when I try to compile the puregotk4 example I get:

```
go build -compiler=gccgo -gccgoflags="-O3 -static-libgo" -o rokon_gccgo .
# github.com/jwijenbergh/purego
../../../go/pkg/mod/github.com/jwijenbergh/purego@v0.0.0-20240527152122-d7876464a49c/syscall_sysv.go:216:3: error: __callbackasm is not a function; ‘//go:linkname’ is only supported for functions
  216 | //go:linkname __callbackasm callbackasm
      |   ^
../../../go/pkg/mod/github.com/jwijenbergh/purego@v0.0.0-20240527152122-d7876464a49c/dlfcn.go:83:3: error: dlclose is not a function; ‘//go:linkname’ is only supported for functions
   83 | //go:linkname dlclose dlclose
      |   ^
../../../go/pkg/mod/github.com/jwijenbergh/purego@v0.0.0-20240527152122-d7876464a49c/dlfcn.go:87:3: error: dlerror is not a function; ‘//go:linkname’ is only supported for functions
   87 | //go:linkname dlerror dlerror
      |   ^
../../../go/pkg/mod/github.com/jwijenbergh/purego@v0.0.0-20240527152122-d7876464a49c/dlfcn.go:75:3: error: dlopen is not a function; ‘//go:linkname’ is only supported for functions
   75 | //go:linkname dlopen dlopen
      |   ^
../../../go/pkg/mod/github.com/jwijenbergh/purego@v0.0.0-20240527152122-d7876464a49c/dlfcn.go:79:3: error: dlsym is not a function; ‘//go:linkname’ is only supported for functions
   79 | //go:linkname dlsym dlsym
      |   ^
  ```
  
  Regardless, I'll go back to using the normal compiler for go. Might be worthwhile tracking this issue

**Comment by jwijenbergh** [comment]
Unfortunately ebitengine/purego doesn't support gccgo so I doubt this will get fixed

**Comment by jwijenbergh** [comment]
Closing as this is an upstream issue
